add other collection measures
wi2trier/cbrkit pull request #127
Opened 2024-05-24 21:36 UTC by Martin-Hoppe

list mapping
list weighted mapping
list correctness

2024-05-27 09:40 UTC, mirkolenz requested changes

2024-05-27 09:40 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +    ) -> tuple[float | Any, list[Any] | Any] | float | Any:
The return type does not correspond to the `SimPairFunc` annotation.

2024-06-04 04:12 UTC, Martin-Hoppe commented on cbrkit/sim/collections.py
> +) -> SimPairFunc[Collection[Any], float]:
Having it as a standalone is closer to the original ProCake though, if thats irrelevant i can change it

2024-06-05 14:43 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +) -> SimPairFunc[Collection[Any], float]:
Yeah I would say that this is irrelevant, cbrkit is already quite different from ProCAKE, so please go ahead and make this a parameter for the `list_mapping` function 😄

2024-06-05 14:52 UTC, mirkolenz requested changes

2024-06-05 14:52 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +    local_similarities: List[float] = None
The types do not match, maybe you mean one of the following?

```suggestion
    local_similarities: List[float] | None = None
```
```suggestion
    local_similarities: List[float] = field(default_factory=list)
```

2024-06-05 14:52 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +    element_similarity: Callable[[Any, Any], float] = None,
Type does not correspond to default value.

2024-06-05 14:52 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +    return_local_similarities: bool = False,
Is this parameter still needed? Now that a dataclass is used (good!), the value could always be added. Or is there some performance impact?

2024-06-05 14:52 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +    normalized_weight: float = None  # Will be set later
Type does not correspond to default value.

```suggestion
    normalized_weight: float | None = None  # Will be set later
```

2024-06-05 14:52 UTC, mirkolenz commented on cbrkit/sim/collections.py
> +    discordant_parameter: float = 1.0,
The naming is a bit odd. What about `worst_case_sim` or `fallback_sim`.

Also, is a default value of `1.0` sensible here? Given the description, I would assume that `0.0` could also make sense.

2024-06-17 09:10 UTC, mirkolenz approved these changes

2024-06-17 09:11 UTC, merged